
INSERT INTO ZACHARIASZ.DEPARTMENT (SHORTCUT, FULLNAME) 
	VALUES ('KASK', 'Katedra Architektury Systemów Komputerowych');
INSERT INTO ZACHARIASZ.DEPARTMENT (SHORTCUT, FULLNAME) 
	VALUES ('KAiMS', 'Katedra Algorytmów i Modelowania Systemów');
INSERT INTO ZACHARIASZ.DEPARTMENT (SHORTCUT, FULLNAME) 
	VALUES ('KIO', 'Katetdra Inżynierii Oprogramowania');

INSERT INTO ZACHARIASZ.STUDENT (FIRSTNAME, LASTNAME, DEPARTMENTID) 
	VALUES ('Jan', 'Nowak', 1);
INSERT INTO ZACHARIASZ.STUDENT (FIRSTNAME, LASTNAME, DEPARTMENTID) 
	VALUES ('Adam', 'Kowalski', 3);
INSERT INTO ZACHARIASZ.STUDENT (FIRSTNAME, LASTNAME, DEPARTMENTID) 
	VALUES ('Wojtek', 'Piotrowski', 2);
INSERT INTO ZACHARIASZ.STUDENT (FIRSTNAME, LASTNAME, DEPARTMENTID) 
	VALUES ('Bartek', 'Kamień', 1);
INSERT INTO ZACHARIASZ.STUDENT (FIRSTNAME, LASTNAME, DEPARTMENTID) 
	VALUES ('Konrad', 'Bąk', 3);
INSERT INTO ZACHARIASZ.STUDENT (FIRSTNAME, LASTNAME, DEPARTMENTID) 
	VALUES ('Katarzyna', 'Sadowska', 2);
INSERT INTO ZACHARIASZ.STUDENT (FIRSTNAME, LASTNAME, DEPARTMENTID) 
	VALUES ('Tomasz', 'Brdak', 1);
INSERT INTO ZACHARIASZ.STUDENT (FIRSTNAME, LASTNAME, DEPARTMENTID) 
	VALUES ('John', 'Bonham', 3);
INSERT INTO ZACHARIASZ.STUDENT (FIRSTNAME, LASTNAME, DEPARTMENTID) 
	VALUES ('Kamil', 'KKK', 2);
